name = "picture-background-remover"
compatibility_date = "2024-01-01"

[env.production]
name = "picture-background-remover"

[[env.production.kv_namespaces]]
binding = "USAGE"
id = ""

[[env.production.secrets]]
name = "REMOVE_BG_API_KEY"
value = "njLZVzRji1mp8jUdAEihtTtp"

[vars]
NEXTAUTH_URL = ""
